# Spring Configuration
spring:
  application:
    name: cart
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mujiki_cart
    username: mujiki_cart
    password: nothing
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:logs/db.changelog-master.xml
    enabled: true

# API Configuration
api:
  endpoint:
    base-url: /api

item:
  url:
    service: http://localhost:8085/api/items

promotion:
  url:
    service: http://localhost:8082/api/promotions

payment:
  url:
    service: http://localhost:8087/api/payment

order:
  url:
    service: http://localhost:8088/api/order



# Server Configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 8083



